fix: Falcon Linux Sensor image is mistakenly used in the container sensor injector
CrowdStrike/falcon-helm pull request #212
Opened 2023-08-02 15:42 UTC by 617m4rc

Fix the situation where an apparently wrong image is used for the sensor injector. This situation can occur in mixed scenarios where parts of the cluster are protected using the Falcon Linux sensor while other parts are protected using the Falcon container sensors.

Use only the container sensor image to avoid conflicts with the enforced PodSecurityPolicies, in particular error "container has runAsNonRoot and image has non-numeric user".

Values for reproduction:

```
node:
  enabled: true
  image:
    repository: xxx.dkr.ecr.eu-central-1.amazonaws.com/falcon-node-sensor

container:
  enabled: true
  image:
    repository: xxx.dkr.ecr.eu-central-1.amazonaws.com/falcon-container-sensor
```

2023-08-11 18:42 UTC, redhatrises commented on helm-charts/falcon-sensor/templates/_helpers.tpl
> +{{- define "falcon-sensor-node.image" -}}
Shouldn't lines 64-72 now be dropped and daemonset/node instances of falcon-sensor.image be changed to "falcon-sensor-node.image"?

2023-08-11 18:42 UTC, redhatrises requested changes

2023-08-11 18:42 UTC, redhatrises commented on helm-charts/falcon-sensor/templates/container_deployment_webhook.yaml
> +        image: "{{ include "falcon-sensor-container.image" . }}"
Make sure the InitContainer has this as well.

2023-08-11 18:44 UTC, redhatrises commented
Hello,

Thank you for your PR. Unfortunately, this still won't fix the entirety of the problem at all since an image name/tag can be anything. Not opposed to these changes, so a couple of things for merging:

1. Drop the `Merge branch 'main' of https://github.com/CrowdStrike/falcon-helm` commit `2d396c1` as we don't want to merge in and dirty up the git history
2. The commit author (y9011) in this case really should be the PR contributor (617m4rc)

2023-08-14 09:28 UTC, 617m4rc commented
This tool is too expensive to fix bugs myself.

2023-08-14 09:28 UTC, closed without merging