chore: update FIG chart to the latest released version 3.2.0
CrowdStrike/falcon-helm pull request #297
Opened 2024-06-14 21:34 UTC by redhatrises

2024-06-14 23:10 UTC, carlosmmatos commented on helm-charts/falcon-integration-gateway/templates/configmap.yaml
> +
```suggestion
    {{- if .Values.credentials_store.secrets_manager.secret_name }}
    secrets_manager_secret_name = {{ .Values.credentials_store.secrets_manager.secret_name }}
    {{- end }}
```

2024-06-14 23:14 UTC, carlosmmatos requested changes
Outside of the requestd change, I think it looks good

2024-06-17 16:14 UTC, redhatrises commented on helm-charts/falcon-integration-gateway/templates/configmap.yaml
> +
Done

2024-06-17 16:16 UTC, carlosmmatos approved these changes

2024-06-17 16:16 UTC, merged

2024-06-18 18:33 UTC, mkeats-clumio commented
@redhatrises there wasn't a 0.4.0 version published in the helm repo for this change. The latest is still 0.3.0
The github action failed due to some unrelated tag already existing https://github.com/CrowdStrike/falcon-helm/actions/runs/9551134785

2024-06-18 23:46 UTC, mkeats-clumio commented
@redhatrises looks like it published after I posted that.

Testing the new version I found a problem with the way you templated out the config

```
    #confirm_instance = true
    {{- if .Values.push.aws_security_hub.confirm_instance }}
    confirm_instance = {{ .Values.push.aws_security_hub.confirm_instance }}
    {{- end }}

```
`{{- if .Values.push.aws_security_hub.confirm_instance }}` is only evaluated true if confirm_instance is set to true. So it makes it impossible to ever override the default true value which I found out when trying to set it to false. We want to check if the value is defined, not if it is true. 

It would be simpler just to remove the conditional and let confirm_instance pick up default value of true if not overridden. This would apply for the other vars too.