Add support for running KAC on hostNetwork
CrowdStrike/falcon-helm pull request #327
Opened 2024-10-18 00:36 UTC by TomRyan-321

This PR introduces support for running KAC on hostNetwork and setting of dnsPolicy which is needed when some scenarios such as when custom CNI's are in use and control plane nodes are not be able to initiate network connections to Calico pods.

Additionally this change adds support for configuring the watcher port and fixes missing webhookPort from being passed to the container client.

Bumps the chart version.

2024-10-21 15:02 UTC, pflanagan-cs approved these changes
LGTM

2024-10-21 15:22 UTC, redhatrises commented
Please rebase and drop commit `fb9aaa8` as it messes with Git history.

2024-10-21 22:22 UTC, gpontejos commented
Please remove the appVersion and version bump.  There will be additional changes added to the release.

2024-10-21 23:11 UTC, TomRyan-321 commented
rebased and removed version bump

2025-01-17 05:58 UTC, TomRyan-321 commented
rebased to main

2025-01-17 14:22 UTC, redhatrises requested changes

2025-01-17 14:22 UTC, redhatrises commented on helm-charts/falcon-kac/templates/deployment_webhook.yaml
> +      dnsPolicy: {{ .Values.dnsPolicy }}
```suggestion
      dnsPolicy: {{ .Values.dnsPolicy }}
```

2025-01-17 14:22 UTC, redhatrises commented on helm-charts/falcon-kac/values.yaml
> +dnsPolicy:
@TomRyan-321 can you set the dnsPolicy default to `ClusterFirstWithHostNet` here instead?

2025-01-17 15:15 UTC, redhatrises commented on helm-charts/falcon-kac/values.yaml
> +dnsPolicy:
@TomRyan-321 right. So, the request is to set the default here instead of in the webhook.yaml

2025-01-17 15:33 UTC, TomRyan-321 commented on helm-charts/falcon-kac/values.yaml
> +dnsPolicy:
Understood updating

2025-01-17 15:56 UTC, redhatrises approved these changes

2025-01-17 15:56 UTC, merged